package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CronologiaFrasi {
    private JPanel panel1;
    private JTextArea textArea1;
    private JButton backButton;
    public JFrame frame;

    public CronologiaFrasi(JFrame frameChiamante, Controller controller, String versionePagina, String titologui) {
        this(frameChiamante, controller.storicoPagina(versionePagina), titologui);
    }
    public CronologiaFrasi(JFrame frameChiamante, Controller controller, int index, String titologui) {
        this(frameChiamante, controller.cronologiaFrasi(index), titologui);
    }
    private CronologiaFrasi(JFrame frameChiamante, String textAreaContent, String titologui) {
        frame = new JFrame(titologui);
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 500);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        textArea1.setEditable(false);
        textArea1.setFocusable(false);
        backButton.setEnabled(true);
        textArea1.append(textAreaContent);


        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        textArea1 = new JTextArea();
        panel1.add(textArea1, BorderLayout.CENTER);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
