package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import controller.Controller;

public class Home {
    private JTextField textField1;
    private JPanel panel1;
    private JButton accediButton;
    private JButton registratiButton;
    private JLabel cercaPaginaLabel;
    private JPanel panelRicerca;
    private JPanel panelAccount;
    private JTextArea textArea1;
    private JButton okButton;
    public static JFrame frame;
    public Controller controller = new Controller();

    public Home() {
        accediButton.setEnabled(true);
        registratiButton.setEnabled(true);
        okButton.setEnabled(true);
        textArea1.setEditable(false);
        textArea1.setFocusable(false);

        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!(textField1.getText().equals(""))) {
                    String testo = controller.recuperaPagina(textField1.getText());
                    if (testo.equals("La pagina non esiste")) {
                        JOptionPane.showMessageDialog(frame, testo, "Errore", JOptionPane.ERROR_MESSAGE);
                    } else if (testo.equals("")) {
                        JOptionPane.showMessageDialog(frame, "La pagina esiste ma è vuota", "Warning", JOptionPane.WARNING_MESSAGE);
                    } else {
                        textArea1.setText("");
                        textArea1.append(testo);
                    }
                }
            }
        });
        accediButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Accesso accesso = new Accesso(frame, controller);
                accesso.frame.setVisible(true);
                frame.setVisible(false);

            }
        });
        registratiButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Registrati registrazione = new Registrati(frame, controller);
                registrazione.frame.setVisible(true);
                frame.setVisible(false);
            }
        });
    }

    public static void main(String[] args) {
        frame = new JFrame("Home");
        frame.setContentPane(new Home().panel1);
        frame.setLocationRelativeTo(null);
        frame.setSize(500, 500);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);

        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panelRicerca = new JPanel();
        panelRicerca.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panelRicerca, BorderLayout.SOUTH);
        accediButton = new JButton();
        accediButton.setText("Accedi");
        panelRicerca.add(accediButton);
        registratiButton = new JButton();
        registratiButton.setText("Registrati");
        panelRicerca.add(registratiButton);
        panelAccount = new JPanel();
        panelAccount.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panelAccount, BorderLayout.NORTH);
        cercaPaginaLabel = new JLabel();
        cercaPaginaLabel.setText("Cerca pagina");
        panelAccount.add(cercaPaginaLabel);
        textField1 = new JTextField();
        textField1.setColumns(10);
        panelAccount.add(textField1);
        okButton = new JButton();
        okButton.setText("Ok");
        panelAccount.add(okButton);
        textArea1 = new JTextArea();
        panel1.add(textArea1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
