package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class InserisciTesto {
    private JTextField fraseField;
    private JPanel panel1;
    private JButton okButton;
    private JButton closeButton;
    private JPanel panel2;
    private JTextArea textArea1;
    public JFrame frame;
    private int ordine = 1;

    public InserisciTesto(Controller controller) {
        frame = new JFrame("Inserisci testo");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 500);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        textArea1.setEditable(false);
        textArea1.setFocusable(false);

        okButton.setEnabled(true);
        closeButton.setEnabled(true);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!(fraseField.getText().equals(""))) {
                    boolean fraseInserita = controller.inserisciFrase(fraseField.getText(), ordine);
                    if (fraseInserita) {
                        textArea1.append(fraseField.getText() + "\n");
                        ordine++;
                        fraseField.setText("");
                    } else {
                        JOptionPane.showMessageDialog(frame, "Frase non inserita", "Errore sql", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ProfiloUtente utente = new ProfiloUtente(controller);
                utente.frame.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        fraseField = new JTextField();
        panel1.add(fraseField, BorderLayout.NORTH);
        panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.SOUTH);
        final JLabel label1 = new JLabel();
        label1.setText("Premi ok per inserire la frase");
        panel2.add(label1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel2.add(okButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel2.add(closeButton);
        textArea1 = new JTextArea();
        panel1.add(textArea1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
