package gui;

import controller.Controller;
import model.Pagina;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class InserisciPagina {
    private JPanel panel1;
    private JTextField titoloField;
    private JPanel titoloPanel;
    private JLabel titolo;
    private JComboBox comboBox1;
    private JButton okButton;
    private JButton backButton;

    public JFrame frame;

    public InserisciPagina(JFrame frameChiamante, Controller controller) {
        frame = new JFrame("Inserisci pagina");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        comboBox1.addItem("Si");
        comboBox1.addItem("No");
        frame.pack();
        frame.setVisible(true);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        okButton.setEnabled(true);
        backButton.setEnabled(true);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (titoloField.getText().equals("")) {
                    JOptionPane.showMessageDialog(frame, "Inserisci il titolo");
                } else {
                    boolean result = controller.inserisciPagina(titoloField.getText());
                    if (result) {
                        JOptionPane.showMessageDialog(frame, "Pagina inserita correttamente");
                        if (comboBox1.getSelectedItem() == "Si") {
                            InserisciTesto testo = new InserisciTesto(controller);
                            testo.frame.setVisible(true);
                            frame.setVisible(false);
                        } else if (comboBox1.getSelectedItem() == "No") {
                            frameChiamante.setVisible(true);
                            frame.setVisible(false);
                            frame.dispose();
                        }
                    } else {
                        JOptionPane.showMessageDialog(frame, "Titolo già esistente");
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        titoloPanel = new JPanel();
        titoloPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(titoloPanel);
        titolo = new JLabel();
        titolo.setText("Titolo");
        titoloPanel.add(titolo);
        titoloField = new JTextField();
        titoloField.setColumns(10);
        titoloPanel.add(titoloField);
        final JLabel label1 = new JLabel();
        label1.setText("Inserire un testo?");
        titoloPanel.add(label1);
        comboBox1 = new JComboBox();
        titoloPanel.add(comboBox1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel1.add(okButton);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
