package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class ListaFrasi {
    private JPanel panel1;
    private JList list1;
    private JButton okButton;
    private JButton backButton;
    private JPanel frasePanel;
    private JLabel fraseLabel;
    public JFrame frame;

    public ListaFrasi(JFrame frameChiamante, Controller controller, int index, String stringaGui) {
        frame = new JFrame(stringaGui);
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        DefaultListModel modelloLista = new DefaultListModel();
        ArrayList<String> frasi = controller.frasiSingole(index);
        if (frasi != null) {
            modelloLista.addAll(frasi);
        } else {
            JOptionPane.showMessageDialog(frame, "errore");
        }

        list1.setModel(modelloLista);
        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        okButton.setEnabled(true);
        backButton.setEnabled(true);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (list1.getSelectedIndices().length == 0) {
                    JOptionPane.showMessageDialog(frame, "Seleziona almeno un elemento.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                } else {
                    if (stringaGui.equals("Cronologia versioni frase")) {
                        System.out.println("INDEX FRASE: " + String.valueOf(list1.getSelectedIndex()));
                        CronologiaFrasi cronologiaFrasi = new CronologiaFrasi(frame, controller, list1.getSelectedIndex(), "Cronologia frasi");
                        cronologiaFrasi.frame.setVisible(true);
                        frame.setVisible(false);
                    } else if (stringaGui.equals("Crea collegamento")) {
                        String ricerca = JOptionPane.showInputDialog(frame, "Cerca la pagina con cui creare il collegamento");
                        if (ricerca != null && ricerca.isEmpty()) {
                            JOptionPane.showMessageDialog(frame, "Inserisci il titolo della pagina", "Error", JOptionPane.ERROR_MESSAGE);
                        } else if (ricerca != null) {
                            boolean cercaPagina = controller.cercaPagina(ricerca);
                            if (cercaPagina) {
                                JOptionPane.showMessageDialog(frame, "La pagina esiste");
                                boolean check = controller.creaCollegamento(list1.getSelectedIndex());
                                if (check) {
                                    JOptionPane.showMessageDialog(frame, "Collegamento creato");
                                } else {
                                    JOptionPane.showMessageDialog(frame, "Errore, la frase ha già un collegamento", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(frame, "La pagina non esiste", "Warning", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                    } else if (stringaGui.equals("Visualizza collegamento")) {
                        String collegamento = controller.visualizzaCollegamento(list1.getSelectedIndex());
                        if (!(collegamento == null)) {
                            JOptionPane.showMessageDialog(frame, "La frase è collegata alla pagina: " + collegamento);
                        } else {
                            JOptionPane.showMessageDialog(frame, "Non sono presenti collegamenti");
                        }
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        frasePanel = new JPanel();
        frasePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(frasePanel);
        fraseLabel = new JLabel();
        fraseLabel.setText("Seleziona una frase");
        frasePanel.add(fraseLabel);
        list1 = new JList();
        frasePanel.add(list1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel1.add(okButton);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
