package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class ListaPagina {
    private JPanel panel1;
    private JList list1;
    private JLabel labelPagina;
    private JPanel paginaPanel;
    private JButton okButton;
    private JButton backButton;
    public JFrame frame;

    public ListaPagina(JFrame frameChiamante, Controller controller, String stringaGui) {
        frame = new JFrame(stringaGui);
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        DefaultListModel modelloLista = new DefaultListModel();
        ArrayList<String> titoli = controller.titoliPagine();
        if (titoli != null) {
            modelloLista.addAll(titoli);
        } else {
            JOptionPane.showMessageDialog(frame, "errore");
        }

        list1.setModel(modelloLista);
        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        okButton.setEnabled(true);
        backButton.setEnabled(true);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (list1.getSelectedIndices().length == 0) {
                    JOptionPane.showMessageDialog(frame, "Seleziona almeno un elemento.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                } else {
                    ArrayList<String> frasi = controller.frasiSingole(list1.getSelectedIndex());
                    if (frasi.isEmpty()) {
                        JOptionPane.showMessageDialog(frame, "Non ci sono frasi per questa pagina", "Attenzione", JOptionPane.WARNING_MESSAGE);
                    } else {
                        ListaFrasi ListaFrasi = new ListaFrasi(frame, controller, list1.getSelectedIndex(), stringaGui);
                        ListaFrasi.frame.setVisible(true);
                        frame.setVisible(false);
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        paginaPanel = new JPanel();
        paginaPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(paginaPanel);
        labelPagina = new JLabel();
        labelPagina.setText("Seleziona pagina");
        paginaPanel.add(labelPagina);
        list1 = new JList();
        paginaPanel.add(list1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel1.add(okButton);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}

