package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class ModificaPagina {
    private JPanel panel1;
    private JList list1;
    private JButton okButton;
    private JButton closeButton;
    private JLabel labelPagina;
    private JPanel panelPagina;
    public JFrame frame;

    public ModificaPagina(JFrame frameChiamante, Controller controller) {
        frame = new JFrame("Pagina da modificare");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        DefaultListModel modelloLista = new DefaultListModel();
        ArrayList<String> titoli = controller.titoliPagine();
        if (titoli != null) {
            modelloLista.addAll(titoli);
        } else {
            JOptionPane.showMessageDialog(frame, "errore");
        }

        list1.setModel(modelloLista);
        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        okButton.setEnabled(true);
        closeButton.setEnabled(true);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (list1.getSelectedIndices().length == 0) {
                    JOptionPane.showMessageDialog(frame, "Seleziona almeno un elemento.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                } else {
                    int confirmChoice = JOptionPane.showConfirmDialog(frame, "Vuoi modificare una frase già esistente?", "Conferma", JOptionPane.YES_NO_OPTION);
                    if (confirmChoice == JOptionPane.YES_OPTION) {
                        ArrayList<String> frasi = controller.frasiSingole(list1.getSelectedIndex());
                        if (frasi.isEmpty()) {
                            JOptionPane.showMessageDialog(frame, "Non ci sono frasi per questa pagina", "Attenzione", JOptionPane.WARNING_MESSAGE);
                            int confermaScelta2 = JOptionPane.showConfirmDialog(frame, "Vuoi inserire nuove frasi?", "Conferma", JOptionPane.YES_NO_OPTION);
                            if (confermaScelta2 == JOptionPane.YES_OPTION) {
                                InserisciTesto2 inserisciTesto = new InserisciTesto2(controller, list1.getSelectedIndex());
                                inserisciTesto.frame.setVisible(true);
                                frame.setVisible(false);
                            }
                        } else {
                            ModificaFrase modificaFrase = new ModificaFrase(frame, controller, list1.getSelectedIndex());
                            modificaFrase.frame.setVisible(true);
                            frame.setVisible(false);
                        }
                    } else {
                        InserisciTesto2 inserisciTesto = new InserisciTesto2(controller, list1.getSelectedIndex());
                        inserisciTesto.frame.setVisible(true);
                        frame.setVisible(false);
                    }
                }
            }
        });
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelPagina = new JPanel();
        panelPagina.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panelPagina);
        labelPagina = new JLabel();
        labelPagina.setText("Seleziona la pagina da modificare");
        panelPagina.add(labelPagina);
        list1 = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        list1.setModel(defaultListModel1);
        panelPagina.add(list1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel1.add(okButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        panel1.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
