package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class ProponiModificaFrase {
    private JPanel panel1;
    private JList list1;
    private JButton okButton;
    private JButton backButton;
    public JFrame frame;

    public ProponiModificaFrase(JFrame frameChiamante, Controller controller, ArrayList<String> frasi) {
        frame = new JFrame("Frase da modificare");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        DefaultListModel modelloLista = new DefaultListModel();
        if (frasi != null) {
            modelloLista.addAll(frasi);
        } else {
            JOptionPane.showMessageDialog(frame, "errore");
        }
        list1.setModel(modelloLista);

        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        okButton.setEnabled(true);
        backButton.setEnabled(true);


        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (list1.getSelectedIndices().length == 0) {
                    JOptionPane.showMessageDialog(frame, "Seleziona almeno un elemento.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                } else {
                    int confirmChoice = JOptionPane.showConfirmDialog(frame, "Vuoi modificare questa frase?", "Message", JOptionPane.YES_NO_OPTION);
                    if (confirmChoice == JOptionPane.YES_OPTION) {
                        String frase = JOptionPane.showInputDialog(frame, "Inserisci la nuova frase modificata");
                        if (frase == null) {
                            JOptionPane.showMessageDialog(frame, "Frase non modificata", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            boolean conferma = controller.proponiFraseMod(frase, list1.getSelectedIndex());
                            if (conferma) {
                                JOptionPane.showMessageDialog(frame, "Proposta di modifica eseguita correttamente");
                                frameChiamante.setVisible(true);
                                frame.setVisible(false);
                                frame.dispose();
                            } else {
                                JOptionPane.showMessageDialog(frame, "errore", "error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(frame, "Operazione annullata");
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2);
        final JLabel label1 = new JLabel();
        label1.setText("Seleziona una frase da modificare");
        panel2.add(label1);
        list1 = new JList();
        panel2.add(list1);
        okButton = new JButton();
        okButton.setText("Ok");
        panel1.add(okButton);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}




