package gui;

import controller.Controller;
import model.Utente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Registrati {
    private JPanel panel1;
    private JTextField nomeField;
    private JPanel nomePanel;
    private JLabel nome;
    private JPanel cognomePanel;
    private JLabel cognome;
    private JTextField cognomeField;
    private JPanel ssnPanel;
    private JTextField ssnField;
    private JLabel ssn;
    private JPanel mailPanel;
    private JTextField mailField;
    private JLabel mail;
    private JPanel passwordPanel;
    private JTextField passwordField;
    private JLabel password;
    private JButton OKButton;
    private JButton homeButton;
    public JFrame frame;

    public Registrati(JFrame frameChiamante, Controller controller) {
        frame = new JFrame("Registrazione");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        OKButton.setEnabled(true);
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ssnField.getText().equals("") || nomeField.getText().equals("") || cognomeField.getText().equals("")
                        || mailField.getText().equals("") || passwordField.getText().equals("")) {
                    JOptionPane.showMessageDialog(frame, "Inserisci tutti i campi");
                } else {
                    boolean registrazione = controller.inserisciUtente(ssnField.getText(), nomeField.getText(), cognomeField.getText(), mailField.getText(), passwordField.getText());
                    if (registrazione) {
                        JOptionPane.showMessageDialog(frame, "Registrazione completata");
                        ProfiloUtente profiloUtente = new ProfiloUtente(controller);
                        profiloUtente.frame.setVisible(true);
                        frame.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(frame, "Inserisci un codice fiscale valido");
                    }
                }
            }
        });
        homeButton.setEnabled(true);
        homeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        nomePanel = new JPanel();
        nomePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(nomePanel);
        nome = new JLabel();
        nome.setText("Nome");
        nomePanel.add(nome);
        nomeField = new JTextField();
        nomeField.setColumns(10);
        nomePanel.add(nomeField);
        cognomePanel = new JPanel();
        cognomePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(cognomePanel);
        cognome = new JLabel();
        cognome.setText("Cognome");
        cognomePanel.add(cognome);
        cognomeField = new JTextField();
        cognomeField.setColumns(10);
        cognomePanel.add(cognomeField);
        ssnPanel = new JPanel();
        ssnPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(ssnPanel);
        ssn = new JLabel();
        ssn.setText("Codice Fiscale");
        ssnPanel.add(ssn);
        ssnField = new JTextField();
        ssnField.setColumns(10);
        ssnPanel.add(ssnField);
        mailPanel = new JPanel();
        mailPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(mailPanel);
        mail = new JLabel();
        mail.setText("Mail");
        mailPanel.add(mail);
        mailField = new JTextField();
        mailField.setColumns(10);
        mailPanel.add(mailField);
        passwordPanel = new JPanel();
        passwordPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(passwordPanel);
        password = new JLabel();
        password.setText("Password");
        passwordPanel.add(password);
        passwordField = new JTextField();
        passwordField.setColumns(10);
        passwordPanel.add(passwordField);
        OKButton = new JButton();
        OKButton.setText("OK");
        panel1.add(OKButton);
        homeButton = new JButton();
        homeButton.setText("Home");
        panel1.add(homeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
