package gui;

import controller.Controller;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class RimuoviPagina {
    private JPanel panel1;
    private JList list1;
    private JPanel rimuoviPanel;
    private JLabel rimuovi;
    private JButton OKButton;
    private JButton backButton;

    public JFrame frame;

    public RimuoviPagina(JFrame frameChiamante, Controller controller) {
        frame = new JFrame("Pagina da rimuovere");
        frame.setContentPane(panel1);
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        DefaultListModel modelloLista = new DefaultListModel();
        ArrayList<String> titoli = controller.titoliPagine();
        if (titoli != null) {
            modelloLista.addAll(titoli);
        } else {
            JOptionPane.showMessageDialog(frame, "errore");
        }

        list1.setModel(modelloLista);
        frame.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width - frame.getWidth()) / 2;
        int y = (screenSize.height - frame.getHeight()) / 2;
        frame.setLocation(x, y);
        frame.setVisible(true);

        OKButton.setEnabled(true);
        backButton.setEnabled(true);

        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (list1.getSelectedIndices().length == 0) {
                    JOptionPane.showMessageDialog(frame, "Seleziona almeno un elemento.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                } else {
                    int confirmChoice = JOptionPane.showConfirmDialog(frame, "Sei sicuro di rimuovere questa pagina?", "Conferma", JOptionPane.YES_NO_OPTION);
                    if (confirmChoice == JOptionPane.YES_OPTION) {
                        boolean paginaEliminata = controller.rimuoviPagina(list1.getSelectedIndex());
                        if (paginaEliminata) {
                            JOptionPane.showMessageDialog(frame, "Pagina eliminata correttamente");
                            frameChiamante.setVisible(true);
                            frame.setVisible(false);
                            frame.dispose();
                        } else {
                            JOptionPane.showMessageDialog(frame, "errore", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else if (confirmChoice == JOptionPane.NO_OPTION) {
                        JOptionPane.showMessageDialog(frame, "Pagina non eliminata");
                    }
                }
            }
        });
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rimuoviPanel = new JPanel();
        rimuoviPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(rimuoviPanel);
        rimuovi = new JLabel();
        rimuovi.setText("Pagina da rimuovere");
        rimuoviPanel.add(rimuovi);
        list1 = new JList();
        rimuoviPanel.add(list1);
        OKButton = new JButton();
        OKButton.setText("OK");
        panel1.add(OKButton);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
